# Filtro pytorch

En este trabajo se muestra el funcionamiento de filtros a imágenes 2d utilizados en redes CNN a través de pytorch.

Simplemente usaremos el módulo de neural network de pytorch.

In [1]:
import torch
import torch.nn as nn

Inicializamos una matriz como un tensor 3 dimensional de floats que represente una imagen. Esta como podemos ver tiene un `batch size` de 1, 3 `input channels`, 3 de `input height` y 10 de `input width`.

In [3]:
input_2d_img = torch.tensor([[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]], [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [
                            1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]], [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]], dtype=torch.float)
input_2d_img = input_2d_img.unsqueeze(0)
input_2d_img.shape

torch.Size([1, 3, 3, 10])

Para los filtros que aplicaremos usaremos `Conv2d` de pytorch la cual nos permite aplicar una convolución 2d con ciertos parámetros a una entrada.

Para este primer filtro utilizamos 3 `canales de entrada` **(como los de nuestra imagen)**, utilizamos 1 `canal de salida`, un tamaño de `kernel`de 3 y finalmente un `stride` para la convolución de 1.

In [4]:
cnn2d_1 = nn.Conv2d(in_channels=3, out_channels=1, kernel_size=3, stride=1)
print("cnn2d_1: \n")
print(cnn2d_1(input_2d_img).shape, "\n")
print(cnn2d_1(input_2d_img))

cnn2d_1: 

torch.Size([1, 1, 1, 8]) 

tensor([[[[0.4645, 1.0574, 1.6503, 2.2432, 2.8361, 3.4290, 4.0218, 4.6147]]]],
       grad_fn=<ConvolutionBackward0>)


Para el segundo filtro utilizamos 3 `canales de entrada` **(como los de nuestra imagen)**, utilizamos 1 `canal de salida`, un tamaño de `kernel`de 3 y finalmente un `stride` para la convolución de 2.

In [5]:
cnn2d_2 = nn.Conv2d(in_channels=3, out_channels=1, kernel_size=3, stride=2)
print("cnn2d_2: \n")
print(cnn2d_2(input_2d_img).shape, "\n")
print(cnn2d_2(input_2d_img))

cnn2d_2: 

torch.Size([1, 1, 1, 4]) 

tensor([[[[1.2704, 1.9867, 2.7031, 3.4195]]]], grad_fn=<ConvolutionBackward0>)


Para este tercer filtro utilizamos 3 `canales de entrada` **(como los de nuestra imagen)**, utilizamos 5 `canales de salida`, un tamaño de `kernel`de 3 y finalmente un `stride` para la convolución de 1.

In [6]:
cnn2d_4 = nn.Conv2d(in_channels=3, out_channels=5, kernel_size=3, stride=1)
print("cnn2d_4: \n")
print(cnn2d_4(input_2d_img).shape, "\n")
print(cnn2d_4(input_2d_img))

cnn2d_4: 

torch.Size([1, 5, 1, 8]) 

tensor([[[[ 1.0049,  1.3614,  1.7178,  2.0743,  2.4307,  2.7871,  3.1436,
            3.5000]],

         [[-0.4538, -0.7888, -1.1237, -1.4586, -1.7936, -2.1285, -2.4635,
           -2.7984]],

         [[ 1.4862,  2.0866,  2.6870,  3.2873,  3.8877,  4.4880,  5.0884,
            5.6888]],

         [[-1.8991, -2.4983, -3.0975, -3.6967, -4.2959, -4.8951, -5.4943,
           -6.0935]],

         [[ 0.9618,  1.3580,  1.7543,  2.1505,  2.5468,  2.9431,  3.3393,
            3.7356]]]], grad_fn=<ConvolutionBackward0>)
