In [5]:
import numpy as np
#a 4 by 4 matrix
matrix = np.zeros((4,4))
print(matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
#7x10 matrix
rand = np.random.randint(0,20,(7,10))
print(rand)

[[12 16 13  6 15  5  1  3  6 19]
 [18  9 16  3  8  1 11  8  9 15]
 [ 9 10 15 19  3  0  3  5 15 16]
 [ 7  4 11 15 13 12 18 19 13  4]
 [14 11 14  3  9  7  9  9  0 19]
 [16 15  9  3 12  5  3 16 17 15]
 [14  3 13  1  8 10 12 10 19 19]]


In [10]:
onesMatrix = np.ones((4,4))
print(onesMatrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [40]:
# imprima diagonal (principal y la otra)
# saque determinante
# suma
# resta
# multiplicación
def calculadora_de_matrices_np(operation, Matrix1, Matrix2):
    if operation == 0:
        return (np.diag(Matrix1),np.diag(np.rot90(Matrix1)))
    elif operation == 1:
        return np.linalg.det(Matrix1)
    elif operation == 2:
        return np.add(Matrix1,Matrix2)
    elif operation == 3:
        return np.subtract(Matrix1,Matrix2)
    elif operation == 4:
        ManualResult = []
        for i in range(len(Matrix1)):
            ManualResult.append([])
            for j in range(len(Matrix2[0])):
                ManualResult[i].append(0)
                for k in range(len(Matrix2)):
                    ManualResult[i][j] += Matrix2[i][k] * Matrix2[k][j]
        return np.array(ManualResult)


Mat1 = np.random.randint(0, 20, (5, 5))
Mat2 = np.random.randint(0, 20, (5, 5))
print("Primera matriz: ")
print(Mat1)
print("Segunda matriz: ")
print(Mat2)
print("Suma: ",calculadora_de_matrices_np(2, Mat1, Mat2))
print("Resta: ",calculadora_de_matrices_np(3, Mat1, Mat2))
print("Multiplicación: ",calculadora_de_matrices_np(4, Mat1, Mat2))
print("Diagonal: ",calculadora_de_matrices_np(0, Mat1, Mat2))
print("Determinante: ",calculadora_de_matrices_np(1, Mat1, Mat2))

Primera matriz: 
[[19 17 13 13 15]
 [17  7 12 11 11]
 [ 8  6  0  4 15]
 [ 6 13 19 14 15]
 [ 7  8 10  7 18]]
Segunda matriz: 
[[15 15  4 18  2]
 [17  5 13 19 10]
 [16 19 14  0 17]
 [11 11 15  5  1]
 [14  8 15  2 18]]
Suma:  [[34 32 17 31 17]
 [34 12 25 30 21]
 [24 25 14  4 32]
 [17 24 34 19 16]
 [21 16 25  9 36]]
Resta:  [[  4   2   9  -5  13]
 [  0   2  -1  -8   1]
 [ -8 -13 -14   4  -2]
 [ -5   2   4   9  14]
 [ -7   0  -5   5   0]]
Multiplicación:  [[ 770  590  611  649  302]
 [ 897  816  750  516  504]
 [1025  737  762  683  766]
 [ 661  568  487  434  410]
 [ 860  701  670  450  689]]
Diagonal:  (array([19,  7,  0, 14, 18]), array([15, 11,  0, 13,  7]))
Determinante:  76157.9999999999


In [47]:
print("¡Bienvenido a la multiplicadora de matrices!\nIngrese las dimensiones de su primera matriz:")
x1 = int(input("x: "))
y1 = int(input("y: "))
print("Ahora llene su primera matriz:")
Matr1 = np.array([[0 for i in range(y1)] for j in range(x1)])
for i in range(x1):
    for j in range(y1):
        Matr1[i][j] = int(input("Ingrese un número: "))
print("Ingrese las dimensiones de su seguna matriz")
x2 = int(input("x: "))
y2 = int(input("y: "))
Matr2 = np.array([[0 for i in range(y2)] for j in range(x2)])
print("Ahora llene su segunda matriz:")
for i in range(x2):
    for j in range(y2):
        Matr2[i][j] = int(input("Ingrese un número: "))
opcion= None
print("Su primera matriz: ")
print(Matr1)
print("Su segunda matriz: ")
print(Matr2)
print(type(Matr1))
print(type(Matr2))
print(Matr1+Matr2)
while(opcion != 5):
    print("Seleccione una operación: \n Para realizar una Suma ingrese 2\n Para realizar una Resta ingrese 3\n Para obtener la diagonal principal y secundaria ingrese 0\n Para realizar la multiplicación ingrese 4\n Para obtener la determinante ingrese 1")
    opcion=int(input("Opcion: "))
    print(calculadora_de_matrices_np(opcion,Matr1,Matr2))


¡Bienvenido a la multiplicadora de matrices!
Ingrese las dimensiones de su primera matriz:
Ahora llene su primera matriz:
Ingrese las dimensiones de su seguna matriz
Ahora llene su segunda matriz:
Su primera matriz: 
[[1 2]
 [3 4]]
Su segunda matriz: 
[[5 6]
 [7 8]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[[ 6  8]
 [10 12]]
Seleccione una operación: 
 Para realizar una Suma ingrese 2
 Para realizar una Resta ingrese 3
 Para obtener la diagonal principal y secundaria ingrese 0
 Para realizar la multiplicación ingrese 4
 Para obtener la determinante ingrese 1
-2.0000000000000004
Seleccione una operación: 
 Para realizar una Suma ingrese 2
 Para realizar una Resta ingrese 3
 Para obtener la diagonal principal y secundaria ingrese 0
 Para realizar la multiplicación ingrese 4
 Para obtener la determinante ingrese 1
[[ 6  8]
 [10 12]]
Seleccione una operación: 
 Para realizar una Suma ingrese 2
 Para realizar una Resta ingrese 3
 Para obtener la diagonal principal y secundaria ingres