# Matrix multiplication using Numpy

In [9]:
import numpy as np
Matrix1 = np.array([[1, 2], [3, 4]])
Matrix2 = np.array([[5, 6], [7, 8]])
print("First Matrix: \n",Matrix1)
print("Second Matrix: \n",Matrix2)
print("Result: \n",np.matmul(Matrix1,Matrix2))

First Matrix: 
 [[1 2]
 [3 4]]
Second Matrix: 
 [[5 6]
 [7 8]]
Result: 
 [[19 22]
 [43 50]]


# Manual approach for matrix multiplication

In [11]:
Manual1 = [[1,2],[3,4]]
Manual2 = [[5,6],[7,8]]
ManualResult = []

for i in range(len(Manual1)):
    ManualResult.append([])
    for j in range(len(Manual2[0])):
        ManualResult[i].append(0)
        for k in range(len(Manual2)):
            ManualResult[i][j] += Manual1[i][k] * Manual2[k][j]
print("Manual Result: \n",ManualResult)

Manual Result: 
 [[19, 22], [43, 50]]
